--- #YAML:1.0
name:               Catalyst-Blinker
version:            1.0
abstract:           show a little X11 blinker while Catalyst is reloading
author:
    - Dmitry Karasik <dmitry@karasik.eu.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:  5.9
    Prima:     0
resources:
    repository:  https://github.com/dk/catalyst-blinker
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
